/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "electricity_state.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MinMaxEntryProto, MinMaxEntryProto, AUTO)


PB_BIND(MinMaxCompositeProto, MinMaxCompositeProto, AUTO)


PB_BIND(DetectedStateProto, DetectedStateProto, AUTO)


PB_BIND(ChangeScoresProto, ChangeScoresProto, AUTO)


PB_BIND(DiffedPowersProto, DiffedPowersProto, AUTO)


PB_BIND(BlinkFieldsProto, BlinkFieldsProto, AUTO)


PB_BIND(HanFieldsProto, HanFieldsProto, 2)


PB_BIND(ElectricityStateProto, ElectricityStateProto, 2)




