# This is the name of the workflow, visible on GitHub UI.
name: compile

# Here we tell GitHub to run the workflow when a commit
# is pushed or a Pull Request is opened.
on:
  push:
    branches: [ main, REL-* ]
  pull_request:
    branches: [ main ]

# This is the list of jobs that will be run concurrently.
# Since we use a build matrix, the actual number of jobs
# started depends on how many configurations the matrix
# will produce.
jobs:
  # This is the name of the job - can be whatever.
  build-compile:

    # Here we tell GitHub that the jobs must be determined
    # dynamically depending on a matrix configuration.
    strategy:
      matrix:
        # The matrix will produce one job for each configuration
        # parameter of type `arduino-platform`, in this case a
        # total of 2.
        arduino-platform: ["esp32:esp32"]
        # This is usually optional but we need to statically define the
        # FQBN of the boards we want to test for each platform. In the
        # future the CLI might automatically detect and download the core
        # needed to compile against a certain FQBN, at that point the
        # following `include` section will be useless.
        include:
          # This works like this: when the platform is "arduino:samd", the
          # variable `fqbn` is set to "arduino:samd:nano_33_iot".
          - arduino-platform: "esp32:esp32"
            fqbn: "esp32:esp32:esp32c3:DebugLevel=info"

    # This is the platform GitHub will use to run our workflow
    runs-on: [self-hosted, Linux]

    # This is the list of steps this job will run.
    steps:
      # First of all, we clone the repo using the `checkout` action.
      - name: Checkout
        uses: actions/checkout@v3

      # Finally, we compile the sketch, using the FQBN that was set
      # in the build matrix.
      - name: Compile
        uses: arduino/compile-sketches@v1.0.1
        with:
          fqbn: ${{ matrix.fqbn }}
          verbose: true
          platforms: |
            - name: "esp32:esp32"
              version: "2.0.7"
              source-url: "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json"
          libraries: |
            - name: log4arduino
            - source-url: git@github.com:me-no-dev/AsyncTCP.git
            - source-url: git@github.com:khoih-prog/ESPAsyncWebServer.git
            - name: MQTT
            - source-url: git@github.com:arduino-libraries/ArduinoHttpClient.git
            - name: ArduinoJson
            - name: Adafruit GFX Library
            - name: Adafruit BusIO
            - name: Adafruit NeoPixel
            - source-url: git@github.com:sosandstrom/sMQTTBroker.git
            - name: SnappyProto
            - name: base64
          cli-compile-flags: |
            - --output-dir
            - ./build
            - --build-property 
            - "compiler.cpp.extra_flags=-DVERSION=\"ci-SNAPSHOT\" -Wno-error=unused-but-set-variable"
          sketch-paths: .
      - name: list results
        run: |
          ls -la ./build/*.bin